# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, verbose_name='删除时间')),
                ('is_deleted', models.NullBooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=11)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('create_time', models.DateTimeField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, verbose_name='删除时间')),
                ('is_deleted', models.NullBooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=11)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('create_time', models.DateTimeField(blank=True)),
                ('category', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, verbose_name='删除时间')),
                ('is_deleted', models.NullBooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=11)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('create_time', models.DateTimeField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('article', models.ManyToManyField(to='blog.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
