# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200327_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='fans',
            name='article',
            field=models.ManyToManyField(related_name='fans', to='blog.Article'),
        ),
    ]
