# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200328_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.SmallIntegerField(blank=True, choices=[(0, '小说'), (1, '论文'), (2, '文章'), (3, '漫画'), (4, '内容'), (5, '微信')], null=True, verbose_name='书籍类型'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='经典书籍评论'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='书籍价格'),
        ),
    ]
