# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200401_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, help_text='剩余书币', verbose_name='剩余书币'),
        ),
    ]
