# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('book_id', models.CharField(blank=True, help_text='源id', max_length=60, null=True)),
                ('last_update', models.DateTimeField(blank=True, help_text='源最新更新时间', null=True)),
                ('name', models.CharField(blank=True, help_text='名称', max_length=30, null=True)),
                ('description', models.CharField(blank=True, help_text='简介', max_length=512, null=True)),
                ('img', models.CharField(blank=True, help_text='封面', max_length=256, null=True)),
                ('author', models.CharField(blank=True, help_text='作者', max_length=16, null=True)),
                ('last_node', models.CharField(blank=True, help_text='最新章节名称', max_length=64, null=True)),
                ('last_node_id', models.CharField(blank=True, help_text='最新章节id', max_length=128, null=True)),
                ('state', models.SmallIntegerField(choices=[(0, '连载'), (1, '完结')], help_text='状态')),
                ('first_node', models.CharField(blank=True, help_text='第一章', max_length=64, null=True)),
                ('node_nums', models.IntegerField(default=0)),
                ('level', models.SmallIntegerField(choices=[(0, '免费'), (1, '福利书')], default=0)),
                ('words', models.BigIntegerField(default=0, help_text='字数')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='类别', max_length=10)),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='父类别')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='名称', max_length=64)),
                ('words', models.IntegerField(default=0, help_text='字数')),
                ('sort_level', models.IntegerField(help_text='排序依据')),
                ('content', models.TextField(help_text='内容')),
                ('book', models.ForeignKey(help_text='书籍', on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='article.Book')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(help_text='分类', on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
    ]
